# Copyright (c) 2024 Digital Asset (Canton) Holdings, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
SFDR (Sustainable Finance Disclosure Regulation) Formatter

This module provides tools to transform structured financial product data,
typically extracted from Canton ledger contracts, into a standardized format
compliant with the SFDR periodic disclosure requirements.

It specifically implements the template for financial products promoting
environmental or social characteristics (Article 8 of SFDR) as detailed in
Annex IV of the Commission Delegated Regulation (EU) 2022/1288 (SFDR RTS).
"""

import json
from datetime import date
from typing import List, Dict, Any, Optional
from decimal import Decimal, InvalidOperation

# A selection of key Principal Adverse Impact (PAI) indicators.
# The keys correspond to fields expected from the Canton data payload.
# This mapping provides a human-readable description for each metric.
PAI_INDICATORS_MAPPING = {
    # Climate and other environment-related indicators
    "ghgEmissionsScope1": "GHG emissions (Scope 1)",
    "ghgEmissionsScope2": "GHG emissions (Scope 2)",
    "ghgEmissionsScope3": "GHG emissions (Scope 3)",
    "totalGhgEmissions": "Total GHG emissions",
    "carbonFootprint": "Carbon footprint (tCO2e / mEUR invested)",
    "ghgIntensityInvestee": "GHG intensity of investee companies (tCO2e / mEUR sales)",
    "exposureToFossilFuels": "Share of investments in companies active in the fossil fuel sector",
    "activitiesNegativelyAffectingBiodiversity": "Share of investments in companies with activities negatively affecting biodiversity-sensitive areas",
    "emissionsToWater": "Tonnes of emissions to water generated by investee companies",
    "hazardousWasteRatio": "Ratio of hazardous waste generated by investee companies",
    # Social and employee, respect for human rights, anti-corruption and anti-bribery matters
    "unadjustedGenderPayGap": "Unadjusted gender pay gap",
    "boardGenderDiversity": "Board gender diversity (% female)",
    "exposureToControversialWeapons": "Share of investments in companies involved in controversial weapons",
    "violationsOfUNGCPrinciples": "Number of investee companies in breach of UN Global Compact principles or OECD Guidelines for Multinational Enterprises",
    "lackOfHumanRightsPolicy": "Share of investee companies without a human rights policy",
}


class SfdrPeriodicReportGenerator:
    """
    Generates an SFDR periodic report from Canton contract data.
    """

    def __init__(self, legal_entity_name: str, reporting_period_start: date, reporting_period_end: date):
        """
        Initializes the report generator.

        Args:
            legal_entity_name: The name of the Financial Market Participant.
            reporting_period_start: The start date of the reporting period.
            reporting_period_end: The end date of the reporting period.
        """
        if reporting_period_end < reporting_period_start:
            raise ValueError("Reporting period end date cannot be before the start date.")

        self.legal_entity_name = legal_entity_name
        self.reporting_period_start = reporting_period_start
        self.reporting_period_end = reporting_period_end

    def generate_report(self, product_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generates the full SFDR periodic report for a single financial product.

        Args:
            product_data: A dictionary representing the payload of a Canton contract
                          for a financial product (e.g., a fund).

        Returns:
            A dictionary representing the structured SFDR report.
        """
        self._validate_product_data(product_data)

        report = {
            "reportMetadata": self._generate_metadata(),
            "productDetails": self._extract_product_details(product_data),
            "environmentalOrSocialCharacteristicsAttainment": self._format_esg_characteristics(product_data),
            "investmentProportions": self._format_investment_proportions(product_data),
            "topInvestments": self._format_top_investments(product_data),
            "principalAdverseImpactsStatement": self._format_pai_statement(product_data),
        }
        return report

    def _validate_product_data(self, data: Dict[str, Any]):
        """Basic validation of the input product data."""
        required_keys = ["productName", "isin", "summary", "investmentProportion", "topHoldings", "paiMetrics"]
        for key in required_keys:
            if key not in data:
                raise ValueError(f"Missing required key in product_data: '{key}'")

    def _generate_metadata(self) -> Dict[str, str]:
        """Creates the metadata section of the report."""
        return {
            "reportType": "SFDR Periodic Disclosure (Article 8 Product)",
            "regulation": "Commission Delegated Regulation (EU) 2022/1288",
            "templateAnnex": "IV",
            "legalEntityName": self.legal_entity_name,
            "reportingPeriod": f"{self.reporting_period_start.isoformat()} to {self.reporting_period_end.isoformat()}",
            "generationTimestamp": date.today().isoformat()
        }

    def _extract_product_details(self, data: Dict[str, Any]) -> Dict[str, str]:
        """Extracts general product details."""
        return {
            "productName": data.get("productName", "N/A"),
            "legalEntityIdentifier": data.get("lei", "N/A"),
            "productIdentifier_ISIN": data.get("isin", "N/A"),
        }

    def _format_esg_characteristics(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Formats the section describing how E/S characteristics were met."""
        return {
            "summary": data.get("summary", "No summary provided."),
            "environmentalAndSocialCharacteristicsMet": data.get("esgCharacteristicsMet", True),
            "performanceOfSustainabilityIndicators": data.get("sustainabilityIndicatorsPerformance", []),
            "actionsTaken": data.get("actionsTaken", "No specific actions reported."),
        }

    def _format_investment_proportions(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Formats the asset allocation breakdown."""
        proportions = data.get("investmentProportion", {})
        try:
            total = sum(Decimal(v) for v in proportions.values())
            if total > Decimal("0") and abs(total - Decimal("1.0")) > Decimal("0.001"):
                print(f"Warning: Investment proportions for {data.get('productName')} sum to {total}, not 1.0.")
        except InvalidOperation:
            raise ValueError("Invalid decimal value found in investmentProportion.")

        return {
            "description": "Proportion of investments used to meet the environmental or social characteristics promoted by the financial product.",
            "breakdown": {k: f"{Decimal(v) * 100:.2f}%" for k, v in proportions.items()},
        }

    def _format_top_investments(self, data: Dict[str, Any]) -> List[Dict[str, str]]:
        """Formats the list of top investments."""
        top_holdings = data.get("topHoldings", [])
        return [
            {
                "investeeCompany": holding.get("name"),
                "country": holding.get("country"),
                "sector": holding.get("sector"),
                "proportionOfInvestments": f"{Decimal(holding.get('weight', '0')) * 100:.2f}%"
            }
            for holding in top_holdings
        ]

    def _format_pai_statement(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Formats the Principal Adverse Impacts statement."""
        pai_metrics = data.get("paiMetrics", {})
        formatted_metrics = [
            {
                "indicator": PAI_INDICATORS_MAPPING[key],
                "value": value,
                "explanation": "This metric reflects the principal adverse impacts on sustainability factors considered by the financial product."
            }
            for key, value in pai_metrics.items() if key in PAI_INDICATORS_MAPPING
        ]

        return {
            "statement": "This financial product considers principal adverse impacts on sustainability factors.",
            "indicators": formatted_metrics,
            "periodCovered": f"{self.reporting_period_start.isoformat()} to {self.reporting_period_end.isoformat()}"
        }


def generate_example_report():
    """
    A standalone function to demonstrate the usage of the SfdrPeriodicReportGenerator
    with sample Canton-like data.
    """
    # Sample data that would be extracted from Canton ledger queries.
    # This represents a single financial product contract.
    sample_fund_contract_payload = {
        "productName": "Green Horizons ESG Fund",
        "isin": "LU1234567890",
        "lei": "549300L3W8JJS1S2S352",
        "summary": (
            "The fund promoted environmental characteristics by investing in companies with low carbon footprints "
            "and social characteristics by focusing on board gender diversity. During the period, these goals were met "
            "as shown by the sustainability indicators."
        ),
        "investmentProportion": {
            "environmentalAlignment": "0.45",
            "socialAlignment": "0.20",
            "other": "0.35"
        },
        "topHoldings": [
            {"name": "SolarWind Power Inc.", "sector": "Renewable Energy", "country": "DE", "weight": "0.085"},
            {"name": "AquaPure Solutions", "sector": "Water Treatment", "country": "FR", "weight": "0.071"},
            {"name": "Inclusive Health PLC", "sector": "Healthcare", "country": "UK", "weight": "0.065"},
            {"name": "Innovatech Software", "sector": "Technology", "country": "US", "weight": "0.050"}
        ],
        "paiMetrics": {
            "carbonFootprint": "55.2",
            "ghgIntensityInvestee": "120.5",
            "boardGenderDiversity": "42.0",
            "unadjustedGenderPayGap": "11.2",
            "exposureToControversialWeapons": "0.0"
        },
        "sustainabilityIndicatorsPerformance": [
            {
                "indicator": "Portfolio Carbon Footprint (tCO2e/mEUR)",
                "target": "< 60.0",
                "actual": "55.2",
                "achieved": True
            },
            {
                "indicator": "Average Board Gender Diversity (%)",
                "target": "> 40.0%",
                "actual": "42.0%",
                "achieved": True
            }
        ],
        "actionsTaken": "Engaged with three portfolio companies on improving their GHG emissions reporting standards."
    }

    # Initialize the generator for a specific reporting entity and period
    generator = SfdrPeriodicReportGenerator(
        legal_entity_name="Global Asset Management SA",
        reporting_period_start=date(2023, 1, 1),
        reporting_period_end=date(2023, 12, 31)
    )

    # Generate the report
    sfdr_report = generator.generate_report(sample_fund_contract_payload)

    # Print the report as a formatted JSON string
    print(json.dumps(sfdr_report, indent=2))

    return sfdr_report


if __name__ == "__main__":
    print("--- Generating Example SFDR Periodic Report ---")
    try:
        generate_example_report()
        print("\n--- Example Report Generation Complete ---")
    except (ValueError, KeyError) as e:
        print(f"\n--- ERROR: Report generation failed: {e} ---")
